#!/bin/bash

. $PREFIX/glibc/opt/termux-style/termux-style
. $PREFIX/glibc/opt/scripts/dialogs
. $PREFIX/glibc/opt/scripts/configs
apply-termux-style
while true; do
load_configs
if [ "$WINEESYNC" = "1" ] && [ "$WINEESYNC_TERMUX" = "0" ]; then
	su -c setenforce 0 &>/dev/null
	sudo mkdir /dev/shm &>/dev/null
	sudo chmod 1777 /dev/shm &>/dev/null
fi
dialog_menu "Mobox" "" \
"1" "Start Wine" \
"2" "Settings" \
"3" "Manage packages" \
"4" "Select current wine container" \
"5" "Change box86 and box64 builds" \
"6" "Patch notes (readme)" \
"7" "Switch to mobox wow64 version (experimental)"
case $? in
1)
	if [ ! -e "$PREFIX/glibc/bin/box86" ] || [ ! -e "$PREFIX/glibc/bin/box64" ]; then
		tar -xf $PREFIX/glibc/opt/box/dec13.tar.xz -C $PREFIX/glibc/bin
	fi
	if [ ! "$WINE_PATH" = "" ] && [ -e "$WINE_PATH" ]; then
		chmod 777 $PREFIX/glibc/opt/scripts/start-tfm
		$PREFIX/glibc/opt/scripts/weg-mod-start
	else
		echo "Selected wine ($(basename $WINE_PATH)) is not installed"
		sleep 3
	fi
;;
2)
	. $PREFIX/glibc/opt/scripts/settings
;;
3)
	load_package-manager
	if [ "$?" = "1" ]; then
		continue
	fi
	defitem_settings=1

	while true; do
	load_configs
	dialog_menu_item $defitem_settings "Install" "" \
	"1" "Install custom wine" \
	"2" "Install wine" \
	"3" "Uninstall wine"
	defitem_settings=$?
	case $defitem_settings in
	1)
		dialog_msgbox "Возможно будет добавлено в следующем обновлении"
;;
	2)
		echo ""
		echo -e "\033[1;97mCurrent wine selected:\033[0m $(basename $WINE_PATH)"
		echo ""
		echo -e "\033[1;97mCan be installed:\033[0m"
		
		j=1
		a=()
		for i in "${wine_packages[@]}"; do
		if [ ! -e "$PREFIX/glibc/$i" ]; then
			echo -e "\033[1;32m$j\033[0m) $i"
			j=$((j+1))
			a+=("$i")
		fi
		done
		echo ""
		echo -en "\033[1;97mSelected number:\033[0m \033[1;33m"
		read i
		echo -e "\033[0m"
		re='^[0-9]+$'
		if [[ $i =~ $re ]] && (( 1 <= $i )) && (( $i <= ${#a[@]} )); then
			i=${a[$i-1]}
			sync-package $i
		fi
	;;
	3)
		echo ""
		echo -e "\033[1;97mCurrent wine selected:\033[0m $(basename $WINE_PATH)"
		echo ""
		echo -e "\033[1;97mCan be uninstalled:\033[0m"
		
		j=1
		a=()
		for i in "${wine_packages[@]}"; do
		if [ -e "$PREFIX/glibc/$i" ]; then
			echo -e "\033[1;32m$j\033[0m) $i"
			j=$((j+1))
			a+=("$i")
		fi
		done
		echo ""
		echo -en "\033[1;97mSelected number:\033[0m \033[1;33m"
		read i
		echo -e "\033[0m"
		re='^[0-9]+$'
		if [[ $i =~ $re ]] && (( 1 <= $i )) && (( $i <= ${#a[@]} )); then
			i=${a[$i-1]}
			remove-package $i
		fi
	;;
	255)
		break
	;;
	esac
	done
;;
4)
	echo ""
	echo -e "\033[1;97mCurrent wine selected:\033[0m $(basename $WINE_PATH)"
	echo ""
	echo -e "\033[1;97mInstalled:\033[0m"
	
	j=1
	a=()
	for i in "${wine_packages[@]}"; do
		if [ -e "$PREFIX/glibc/$i" ]; then
			echo -e "\033[1;32m$j\033[0m) $i"
			j=$((j+1))
			a+=("$i")
		fi
	done
	echo ""
	echo -en "\033[1;97mSelected number:\033[0m \033[1;33m"
	read i
	echo -e "\033[0m"
	re='^[0-9]+$'
	if [[ $i =~ $re ]] && (( 1 <= $i )) && (( $i <= ${#a[@]} )); then
		i=${a[$i-1]}
		echo "export WINE_PATH=\$PREFIX/glibc/$i
export WINEPREFIX=\$PREFIX/glibc/$i/.wine">$PREFIX/glibc/opt/conf/wine_path.conf
	fi
	sleep 1
;;
5)
	dialog_menu "Change box86 and box64 builds" "" \
	"1" "Nov 10 builds" \
	"2" "Dec 23 builds (default)" \
	"3" "Jan 18 builds (box64 issues reported)"
	case $? in
	1)
		tar -xf $PREFIX/glibc/opt/box/nov10.tar.xz -C $PREFIX/glibc/bin
	;;
	2)
		tar -xf $PREFIX/glibc/opt/box/dec23.tar.xz -C $PREFIX/glibc/bin
	;;
	3)
		tar -xf $PREFIX/glibc/opt/box/jan18.tar.xz -C $PREFIX/glibc/bin
	;;
	esac
;;
6)
	dialog_msgbox "Patch notes" "\Z3Jan 15\Zn
1. Added new wine-ge-custom-8-25
2. Fixed OOM Adjuster
3. Added WINE ESYNC for all users.
4. Replaced winedevice.exe kill with all services kill
5. Fixed VKD3D for Elden Ring
\Z3Jan 18\Zn
1. Added experimental media foundation codecs for 64 bit RE games, available in start menu
2. Updated box builds, installed by default
\Z3Jan 19\Zn
1. Reverted boxes update...
\Z3Not being implemented for now, planned\Zn
dxvk settings in start menu, xinput"
;;
7)
	dialog_yesno "Backup your games and game saves in C:\\, C:\\ProgramData, AppData before updating mobox! Do you want to uninstall current mobox and install new version now?"
	if [ "$?" = "0" ]; then
		restore-termux-style
		curl -s -o ~/x https://raw.githubusercontent.com/olegos2/mobox/main/install && . ~/x
		break
	fi
;;
255)
	break
;;
esac
done
restore-termux-style
